/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/submitAmount": {
    /**
     * Submit amount
     * @description Endpoint to submit an amount
     */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** @example 100.5 */
            amount?: number;
          };
        };
      };
      responses: {
        /** @description Successful submission */
        200: {
          content: {
            "application/json": {
              /** @example true */
              success?: boolean;
              /** @example Amount submitted successfully. */
              message?: string;
            };
          };
        };
        /** @description Invalid input */
        400: {
          content: {
            "application/json": {
              /** @example false */
              success?: boolean;
              /** @example Invalid input data. */
              error?: string;
            };
          };
        };
      };
    };
  };
  "/submitResponse": {
    /**
     * Submit response
     * @description Endpoint to submit a response
     */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /**
             * @example Agreed
             * @enum {string}
             */
            response?: "Objected" | "Agreed";
          };
        };
      };
      responses: {
        /** @description Successful submission */
        200: {
          content: {
            "application/json": {
              /** @example true */
              success?: boolean;
              /** @example Response submitted successfully. */
              message?: string;
            };
          };
        };
        /** @description Invalid input */
        400: {
          content: {
            "application/json": {
              /** @example false */
              success?: boolean;
              /** @example Invalid input data. */
              error?: string;
            };
          };
        };
      };
    };
  };
  "/getResponse": {
    /**
     * Get response
     * @description Endpoint to get the response
     */
    get: {
      responses: {
        /** @description Successful retrieval */
        200: {
          content: {
            "application/json": {
              /**
               * @example Agreed
               * @enum {string}
               */
              response?: "Objected" | "Agreed";
            };
          };
        };
        /** @description Response not found */
        404: {
          content: {
            "application/json": {
              /** @example false */
              success?: boolean;
              /** @example Response not found. */
              error?: string;
            };
          };
        };
      };
    };
  };
  "/getAmount": {
    /**
     * Get amount
     * @description Endpoint to get the amount
     */
    get: {
      responses: {
        /** @description Successful retrieval */
        200: {
          content: {
            "application/json": {
              /** @example 100.5 */
              amount?: number;
            };
          };
        };
        /** @description Amount not found */
        404: {
          content: {
            "application/json": {
              /** @example false */
              success?: boolean;
              /** @example Amount not found. */
              error?: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Amount: {
      amount?: number;
    };
    Response: {
      /** @enum {string} */
      response?: "Objected" | "Agreed";
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
